# Generated by Django 4.2 on 2023-05-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('sem_period', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='second_school',
            new_name='secondary_school',
        ),
    ]
